// AUTO-SYNCED — do not edit by hand.
// Written by web/scripts/sync-chain.mjs from the Foundry artifacts in contracts/out
// and contracts/deployed.json. Refresh with: npm run sync-chain

/** The live deployment, copied from contracts/deployed.json when this file was written. */
export const deployed = {
  chainId: 50312,
  /** ERC-1167 master copy every user desk is cloned from. Never call it directly. */
  deskImplementation: '0x8D87D72A23Be0F9a07046b89113a7e615F629994',
  brain: '0x0c640E3aFc627bEec7eDB9985696e12B50AdAd25',
  /** Sole owner of every reactivity subscription; must hold >= 32 SOMI to keep them alive. */
  router: '0x6aE21a20444141552648C1f8443bAf171BCCcB99',
  factory: '0xF36b6E1cf0D43563bC8874dd0cf8c24188eE2d94',
  keeper: '0x4757599dC9A5a089270373a66BEeeD6592788707',
  relay: '0xd9Eee9BE420E2CD777E55d890a940a637ed0bB7A',
  series: '0x747fF3a7A6FE4912c96dCe7faA711dCB6fbd1CE4',
  /** The market creator LucidSeries rolls a window through when the venue's scheduler stalls. */
  marketCreator: '0x7Fa6Ac2a61C0b5A0FcC7E1d9b05a0F6AD84763b2',
  /** The DreamDEX venue the router is armed against. */
  venueId: '0x1a1e6821cde7d0159c0d293177871e09677b4e42307c7db3ba94f8648a5a050f',
  /** Our own venue, used only by the failover roller. */
  ownVenueId: '0x7b41ffa006bd7ef1b8a539217694d4db48a2b07784690decbf6b0bc9d61e8581',
  /**
   * Desks deployed alongside the protocol, so a build with no network still has a page to
   * pre-render. The deploy script names them by strategy and the set changes between
   * deployments, so they are collected by shape rather than by a fixed key.
   */
  seedDesks: ['0x7a3153D5f0142F12dDe38A16E550098AFf4f58c0', '0xb8d3d87cfF214A2c1DC56bdAbe182b8165Db5644'] as readonly string[],
} as const

export const routerAbi = [
  {"type":"constructor","inputs":[{"name":"owner_","type":"address"},{"name":"brain_","type":"address"}],"stateMutability":"nonpayable"},
  {"type":"receive","stateMutability":"payable"},
  {"type":"function","name":"BOOK_GAS","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"DECISION_POINT_BPS","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"DESK_GAS","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"GAS_RESERVE","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"HANDLER_GAS_LIMIT","inputs":[],"outputs":[{"name":"","type":"uint64"}],"stateMutability":"view"},
  {"type":"function","name":"HANDLER_MAX_FEE","inputs":[],"outputs":[{"name":"","type":"uint64"}],"stateMutability":"view"},
  {"type":"function","name":"HANDLER_PRIORITY_FEE","inputs":[],"outputs":[{"name":"","type":"uint64"}],"stateMutability":"view"},
  {"type":"function","name":"KEEPER_GAS","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"MAX_DECISION_POINT_BPS","inputs":[],"outputs":[{"name":"","type":"uint16"}],"stateMutability":"view"},
  {"type":"function","name":"MAX_DRAIN","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"MAX_FANOUT","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"MAX_SCALE_BPS","inputs":[],"outputs":[{"name":"","type":"uint16"}],"stateMutability":"view"},
  {"type":"function","name":"MAX_SCAN","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"MIN_DECISION_POINT_BPS","inputs":[],"outputs":[{"name":"","type":"uint16"}],"stateMutability":"view"},
  {"type":"function","name":"PRECHECK_GAS","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"RELAY_BATCH","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"RELAY_GAS","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"SERIES_GAS","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"SETTLEMENT_BUDGET","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"SETTLEMENT_DELAY","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"SUBSCRIPTION_FLOOR","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"allDesks","inputs":[],"outputs":[{"name":"","type":"address[]"}],"stateMutability":"view"},
  {"type":"function","name":"armVenue","inputs":[{"name":"module","type":"address"},{"name":"venueId_","type":"bytes32"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"armedDesks","inputs":[],"outputs":[{"name":"out","type":"address[]"}],"stateMutability":"view"},
  {"type":"function","name":"brain","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"decisionPointBps","inputs":[],"outputs":[{"name":"","type":"uint16"}],"stateMutability":"view"},
  {"type":"function","name":"decisionPointOf","inputs":[{"name":"m","type":"tuple","components":[{"name":"marketId","type":"bytes32"},{"name":"market","type":"address"},{"name":"pool","type":"address"},{"name":"operatorId","type":"uint32"},{"name":"venueId","type":"bytes32"},{"name":"yesId","type":"uint256"},{"name":"noId","type":"uint256"},{"name":"tradingStart","type":"uint64"},{"name":"expiry","type":"uint64"},{"name":"nonce","type":"uint64"},{"name":"strike","type":"uint256"},{"name":"assetKey","type":"bytes32"},{"name":"intervalSec","type":"uint32"}]}],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"decisionQueueLength","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"decodeMarket","inputs":[{"name":"topics","type":"bytes32[]"},{"name":"data","type":"bytes"}],"outputs":[{"name":"","type":"tuple","components":[{"name":"marketId","type":"bytes32"},{"name":"market","type":"address"},{"name":"pool","type":"address"},{"name":"operatorId","type":"uint32"},{"name":"venueId","type":"bytes32"},{"name":"yesId","type":"uint256"},{"name":"noId","type":"uint256"},{"name":"tradingStart","type":"uint64"},{"name":"expiry","type":"uint64"},{"name":"nonce","type":"uint64"},{"name":"strike","type":"uint256"},{"name":"assetKey","type":"bytes32"},{"name":"intervalSec","type":"uint32"}]}],"stateMutability":"pure"},
  {"type":"function","name":"deskArmed","inputs":[{"name":"desk","type":"address"}],"outputs":[{"name":"","type":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"factory","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"gasCreditOf","inputs":[{"name":"desk","type":"address"}],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"interestedIn","inputs":[{"name":"marketId","type":"bytes32"}],"outputs":[{"name":"","type":"address[]"}],"stateMutability":"view"},
  {"type":"function","name":"isDesk","inputs":[{"name":"desk","type":"address"}],"outputs":[{"name":"","type":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"keeper","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"marketOf","inputs":[{"name":"marketId","type":"bytes32"}],"outputs":[{"name":"","type":"tuple","components":[{"name":"marketId","type":"bytes32"},{"name":"market","type":"address"},{"name":"pool","type":"address"},{"name":"operatorId","type":"uint32"},{"name":"venueId","type":"bytes32"},{"name":"yesId","type":"uint256"},{"name":"noId","type":"uint256"},{"name":"tradingStart","type":"uint64"},{"name":"expiry","type":"uint64"},{"name":"nonce","type":"uint64"},{"name":"strike","type":"uint256"},{"name":"assetKey","type":"bytes32"},{"name":"intervalSec","type":"uint32"}]}],"stateMutability":"view"},
  {"type":"function","name":"onEvent","inputs":[{"name":"emitter","type":"address"},{"name":"eventTopics","type":"bytes32[]"},{"name":"data","type":"bytes"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"onVerdict","inputs":[{"name":"marketId","type":"bytes32"},{"name":"v","type":"tuple","components":[{"name":"probUpBps","type":"uint16"},{"name":"responded","type":"uint8"},{"name":"agreed","type":"uint8"},{"name":"ok","type":"bool"},{"name":"requestId","type":"uint256"}]}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"owner","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"pendingDecisions","inputs":[],"outputs":[{"name":"","type":"tuple[]","components":[{"name":"marketId","type":"bytes32"},{"name":"dueAtSec","type":"uint64"}]}],"stateMutability":"view"},
  {"type":"function","name":"pendingSettlements","inputs":[],"outputs":[{"name":"","type":"tuple[]","components":[{"name":"marketId","type":"bytes32"},{"name":"dueAtSec","type":"uint64"}]}],"stateMutability":"view"},
  {"type":"function","name":"recentOf","inputs":[{"name":"assetKey","type":"bytes32"}],"outputs":[{"name":"out","type":"uint16[]"}],"stateMutability":"view"},
  {"type":"function","name":"registerDesk","inputs":[{"name":"desk","type":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"relay","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"renounceOwnership","inputs":[],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"reportTrade","inputs":[{"name":"marketId","type":"bytes32"},{"name":"kind","type":"uint8"},{"name":"stake","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"scheduleIdAt","inputs":[{"name":"tsMillis","type":"uint256"}],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"scheduleSettlement","inputs":[{"name":"tsMillis","type":"uint256"}],"outputs":[{"name":"subscriptionId","type":"uint256"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"series","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"setBrain","inputs":[{"name":"brain_","type":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setDecisionPoint","inputs":[{"name":"bps","type":"uint16"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setDeskArmed","inputs":[{"name":"desk","type":"address"},{"name":"on","type":"bool"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setFactory","inputs":[{"name":"factory_","type":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setKeeper","inputs":[{"name":"keeper_","type":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setRelay","inputs":[{"name":"relay_","type":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setSeries","inputs":[{"name":"series_","type":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"settlementBooked","inputs":[{"name":"marketId","type":"bytes32"}],"outputs":[{"name":"","type":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"settlementQueueLength","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"supportsInterface","inputs":[{"name":"interfaceId","type":"bytes4"}],"outputs":[{"name":"","type":"bool"}],"stateMutability":"pure"},
  {"type":"function","name":"sweep","inputs":[{"name":"to","type":"address"},{"name":"amount","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"topUp","inputs":[{"name":"desk","type":"address"}],"outputs":[],"stateMutability":"payable"},
  {"type":"function","name":"totalGasCredit","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"transferOwnership","inputs":[{"name":"newOwner","type":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"venue","inputs":[],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"venueModule","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"venueSubscriptionId","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"event","name":"BrainUpdated","inputs":[{"name":"brain","type":"address","indexed":false}],"anonymous":false},
  {"type":"event","name":"Debited","inputs":[{"name":"desk","type":"address","indexed":true},{"name":"marketId","type":"bytes32","indexed":true},{"name":"amount","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"DecisionPointSet","inputs":[{"name":"bps","type":"uint16","indexed":false}],"anonymous":false},
  {"type":"event","name":"DecisionScheduled","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"tsMillis","type":"uint256","indexed":false},{"name":"subscriptionId","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"DeskArmed","inputs":[{"name":"desk","type":"address","indexed":true},{"name":"on","type":"bool","indexed":false}],"anonymous":false},
  {"type":"event","name":"DeskRegistered","inputs":[{"name":"desk","type":"address","indexed":true}],"anonymous":false},
  {"type":"event","name":"DrainStopped","inputs":[{"name":"decisions","type":"bool","indexed":false},{"name":"drained","type":"uint256","indexed":false},{"name":"remaining","type":"uint256","indexed":false},{"name":"reason","type":"string","indexed":false}],"anonymous":false},
  {"type":"event","name":"FactoryUpdated","inputs":[{"name":"factory","type":"address","indexed":false}],"anonymous":false},
  {"type":"event","name":"KeeperSet","inputs":[{"name":"keeper","type":"address","indexed":false}],"anonymous":false},
  {"type":"event","name":"MarketSeen","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"intervalSec","type":"uint32","indexed":false},{"name":"assetKey","type":"bytes32","indexed":false}],"anonymous":false},
  {"type":"event","name":"OwnershipTransferred","inputs":[{"name":"previousOwner","type":"address","indexed":true},{"name":"newOwner","type":"address","indexed":true}],"anonymous":false},
  {"type":"event","name":"RelaySet","inputs":[{"name":"relay","type":"address","indexed":false}],"anonymous":false},
  {"type":"event","name":"SeriesSet","inputs":[{"name":"series","type":"address","indexed":false}],"anonymous":false},
  {"type":"event","name":"SettlementScheduled","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"tsMillis","type":"uint256","indexed":false},{"name":"subscriptionId","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"Skipped","inputs":[{"name":"desk","type":"address","indexed":true},{"name":"marketId","type":"bytes32","indexed":true},{"name":"reason","type":"string","indexed":false}],"anonymous":false},
  {"type":"event","name":"Swept","inputs":[{"name":"to","type":"address","indexed":true},{"name":"amount","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"ToppedUp","inputs":[{"name":"desk","type":"address","indexed":true},{"name":"amount","type":"uint256","indexed":false},{"name":"balance","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"TradeReported","inputs":[{"name":"desk","type":"address","indexed":true},{"name":"marketId","type":"bytes32","indexed":true},{"name":"kind","type":"uint8","indexed":false},{"name":"stake","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"VenueArmed","inputs":[{"name":"venueId","type":"bytes32","indexed":false},{"name":"subscriptionId","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"VerdictRequested","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"fee","type":"uint256","indexed":false},{"name":"deskCount","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"error","name":"BadDecisionPoint","inputs":[{"name":"bps","type":"uint16"}]},
  {"type":"error","name":"CreditsLocked","inputs":[{"name":"available","type":"uint256"},{"name":"requested","type":"uint256"}]},
  {"type":"error","name":"EmptyFilter","inputs":[]},
  {"type":"error","name":"GasLimitExceeded","inputs":[]},
  {"type":"error","name":"GasLimitZero","inputs":[]},
  {"type":"error","name":"HandlerZeroAddress","inputs":[]},
  {"type":"error","name":"InsufficientBalance","inputs":[]},
  {"type":"error","name":"InvalidMaxFeePerGas","inputs":[]},
  {"type":"error","name":"NotAContract","inputs":[{"name":"account","type":"address"}]},
  {"type":"error","name":"NotBrain","inputs":[]},
  {"type":"error","name":"NotDesk","inputs":[]},
  {"type":"error","name":"NotFactory","inputs":[]},
  {"type":"error","name":"NotSelf","inputs":[]},
  {"type":"error","name":"OnlyReactivityPrecompile","inputs":[]},
  {"type":"error","name":"OwnableInvalidOwner","inputs":[{"name":"owner","type":"address"}]},
  {"type":"error","name":"OwnableUnauthorizedAccount","inputs":[{"name":"account","type":"address"}]},
  {"type":"error","name":"RouterUnderfunded","inputs":[{"name":"have","type":"uint256"},{"name":"need","type":"uint256"}]},
  {"type":"error","name":"SweepFailed","inputs":[]},
  {"type":"error","name":"TimestampInPast","inputs":[]},
  {"type":"error","name":"TopicCountMismatch","inputs":[{"name":"got","type":"uint256"}]},
  {"type":"error","name":"UnexpectedEvent","inputs":[{"name":"topic0","type":"bytes32"}]},
  {"type":"error","name":"UnknownDesk","inputs":[{"name":"desk","type":"address"}]},
  {"type":"error","name":"UnsubscribeFailed","inputs":[]},
  {"type":"error","name":"ZeroAddress","inputs":[]},
] as const

export const deskAbi = [
  {"type":"constructor","inputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"approved","inputs":[{"name":"","type":"address"}],"outputs":[{"name":"","type":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"arm","inputs":[{"name":"on","type":"bool"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"brain","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"deposit","inputs":[{"name":"amount","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"equity","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"fundFromFaucet","inputs":[{"name":"amount","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"held","inputs":[{"name":"","type":"bytes32"}],"outputs":[{"name":"cost","type":"uint128"},{"name":"open","type":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"initialize","inputs":[{"name":"owner_","type":"address"},{"name":"router_","type":"address"},{"name":"brain_","type":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"onLeaderTrade","inputs":[{"name":"m","type":"tuple","components":[{"name":"marketId","type":"bytes32"},{"name":"market","type":"address"},{"name":"pool","type":"address"},{"name":"operatorId","type":"uint32"},{"name":"venueId","type":"bytes32"},{"name":"yesId","type":"uint256"},{"name":"noId","type":"uint256"},{"name":"tradingStart","type":"uint64"},{"name":"expiry","type":"uint64"},{"name":"nonce","type":"uint64"},{"name":"strike","type":"uint256"},{"name":"assetKey","type":"bytes32"},{"name":"intervalSec","type":"uint32"}]},{"name":"kind","type":"uint8"},{"name":"stake","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"onSettlement","inputs":[{"name":"m","type":"tuple","components":[{"name":"marketId","type":"bytes32"},{"name":"market","type":"address"},{"name":"pool","type":"address"},{"name":"operatorId","type":"uint32"},{"name":"venueId","type":"bytes32"},{"name":"yesId","type":"uint256"},{"name":"noId","type":"uint256"},{"name":"tradingStart","type":"uint64"},{"name":"expiry","type":"uint64"},{"name":"nonce","type":"uint64"},{"name":"strike","type":"uint256"},{"name":"assetKey","type":"bytes32"},{"name":"intervalSec","type":"uint32"}]}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"onVerdict","inputs":[{"name":"m","type":"tuple","components":[{"name":"marketId","type":"bytes32"},{"name":"market","type":"address"},{"name":"pool","type":"address"},{"name":"operatorId","type":"uint32"},{"name":"venueId","type":"bytes32"},{"name":"yesId","type":"uint256"},{"name":"noId","type":"uint256"},{"name":"tradingStart","type":"uint64"},{"name":"expiry","type":"uint64"},{"name":"nonce","type":"uint64"},{"name":"strike","type":"uint256"},{"name":"assetKey","type":"bytes32"},{"name":"intervalSec","type":"uint32"}]},{"name":"v","type":"tuple","components":[{"name":"probUpBps","type":"uint16"},{"name":"responded","type":"uint8"},{"name":"agreed","type":"uint8"},{"name":"ok","type":"bool"},{"name":"requestId","type":"uint256"}]},{"name":"pBookBps","type":"uint256"},{"name":"bookObserved","type":"bool"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"openNotional","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"owner","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"policy","inputs":[],"outputs":[{"name":"","type":"tuple","components":[{"name":"maxStakePerWindow","type":"uint64"},{"name":"dailyBudget","type":"uint64"},{"name":"maxOpenMarkets","type":"uint16"},{"name":"maxDrawdownBps","type":"uint16"},{"name":"maxConsecutiveLosses","type":"uint8"},{"name":"minEdgeBps","type":"uint16"},{"name":"allowedAssets","type":"uint32"},{"name":"allowedCadences","type":"uint32"},{"name":"strategy","type":"uint8"},{"name":"armed","type":"bool"}]}],"stateMutability":"view"},
  {"type":"function","name":"preCheck","inputs":[{"name":"m","type":"tuple","components":[{"name":"marketId","type":"bytes32"},{"name":"market","type":"address"},{"name":"pool","type":"address"},{"name":"operatorId","type":"uint32"},{"name":"venueId","type":"bytes32"},{"name":"yesId","type":"uint256"},{"name":"noId","type":"uint256"},{"name":"tradingStart","type":"uint64"},{"name":"expiry","type":"uint64"},{"name":"nonce","type":"uint64"},{"name":"strike","type":"uint256"},{"name":"assetKey","type":"bytes32"},{"name":"intervalSec","type":"uint32"}]}],"outputs":[{"name":"","type":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"router","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"setPolicy","inputs":[{"name":"p","type":"tuple","components":[{"name":"maxStakePerWindow","type":"uint64"},{"name":"dailyBudget","type":"uint64"},{"name":"maxOpenMarkets","type":"uint16"},{"name":"maxDrawdownBps","type":"uint16"},{"name":"maxConsecutiveLosses","type":"uint8"},{"name":"minEdgeBps","type":"uint16"},{"name":"allowedAssets","type":"uint32"},{"name":"allowedCadences","type":"uint32"},{"name":"strategy","type":"uint8"},{"name":"armed","type":"bool"}]}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"state","inputs":[],"outputs":[{"name":"","type":"tuple","components":[{"name":"dayKey","type":"uint64"},{"name":"spentToday","type":"uint64"},{"name":"highWaterMark","type":"uint64"},{"name":"openMarkets","type":"uint16"},{"name":"consecutiveLosses","type":"uint8"}]}],"stateMutability":"view"},
  {"type":"function","name":"withdraw","inputs":[{"name":"amount","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"event","name":"ArmedSet","inputs":[{"name":"on","type":"bool","indexed":false}],"anonymous":false},
  {"type":"event","name":"Considered","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"intervalSec","type":"uint32","indexed":false},{"name":"assetKey","type":"bytes32","indexed":false}],"anonymous":false},
  {"type":"event","name":"Executed","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"kind","type":"uint8","indexed":false},{"name":"price","type":"uint256","indexed":false},{"name":"quantity","type":"uint256","indexed":false},{"name":"orderId","type":"uint128","indexed":false}],"anonymous":false},
  {"type":"event","name":"PolicySet","inputs":[{"name":"policy","type":"tuple","indexed":false,"components":[{"name":"maxStakePerWindow","type":"uint64"},{"name":"dailyBudget","type":"uint64"},{"name":"maxOpenMarkets","type":"uint16"},{"name":"maxDrawdownBps","type":"uint16"},{"name":"maxConsecutiveLosses","type":"uint8"},{"name":"minEdgeBps","type":"uint16"},{"name":"allowedAssets","type":"uint32"},{"name":"allowedCadences","type":"uint32"},{"name":"strategy","type":"uint8"},{"name":"armed","type":"bool"}]}],"anonymous":false},
  {"type":"event","name":"Refused","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"reason","type":"uint8","indexed":false},{"name":"probUpBps","type":"uint16","indexed":false},{"name":"pBookBps","type":"uint16","indexed":false}],"anonymous":false},
  {"type":"event","name":"Settled","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"pnl","type":"int256","indexed":false},{"name":"equityAfter","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"VerdictReceived","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"probUpBps","type":"uint16","indexed":false},{"name":"pBookBps","type":"uint16","indexed":false},{"name":"responded","type":"uint8","indexed":false}],"anonymous":false},
  {"type":"error","name":"AlreadyInitialized","inputs":[]},
  {"type":"error","name":"NotOwner","inputs":[]},
  {"type":"error","name":"NotRouter","inputs":[]},
  {"type":"error","name":"TransferFailed","inputs":[]},
  {"type":"error","name":"ZeroAddress","inputs":[]},
] as const

export const factoryAbi = [
  {"type":"constructor","inputs":[{"name":"implementation_","type":"address"},{"name":"router_","type":"address"},{"name":"brain_","type":"address"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"MAX_FOLLOWERS","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"allDesks","inputs":[],"outputs":[{"name":"","type":"address[]"}],"stateMutability":"view"},
  {"type":"function","name":"brain","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"createDesk","inputs":[{"name":"p","type":"tuple","components":[{"name":"maxStakePerWindow","type":"uint64"},{"name":"dailyBudget","type":"uint64"},{"name":"maxOpenMarkets","type":"uint16"},{"name":"maxDrawdownBps","type":"uint16"},{"name":"maxConsecutiveLosses","type":"uint8"},{"name":"minEdgeBps","type":"uint16"},{"name":"allowedAssets","type":"uint32"},{"name":"allowedCadences","type":"uint32"},{"name":"strategy","type":"uint8"},{"name":"armed","type":"bool"}]}],"outputs":[{"name":"desk","type":"address"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"deskCount","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"deskOf","inputs":[{"name":"user","type":"address"}],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"follow","inputs":[{"name":"leader","type":"address"},{"name":"scaleBps","type":"uint16"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"followersOf","inputs":[{"name":"leader","type":"address"}],"outputs":[{"name":"","type":"address[]"}],"stateMutability":"view"},
  {"type":"function","name":"implementation","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"isPublished","inputs":[{"name":"desk","type":"address"}],"outputs":[{"name":"","type":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"publish","inputs":[{"name":"name","type":"string"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"publishedDesks","inputs":[],"outputs":[{"name":"","type":"address[]"}],"stateMutability":"view"},
  {"type":"function","name":"router","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"scaleOf","inputs":[{"name":"leader","type":"address"},{"name":"follower","type":"address"}],"outputs":[{"name":"","type":"uint16"}],"stateMutability":"view"},
  {"type":"function","name":"strategyName","inputs":[{"name":"desk","type":"address"}],"outputs":[{"name":"","type":"string"}],"stateMutability":"view"},
  {"type":"function","name":"unfollow","inputs":[{"name":"leader","type":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"unpublish","inputs":[],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"event","name":"DeskCreated","inputs":[{"name":"owner","type":"address","indexed":true},{"name":"desk","type":"address","indexed":true}],"anonymous":false},
  {"type":"event","name":"Followed","inputs":[{"name":"leader","type":"address","indexed":true},{"name":"follower","type":"address","indexed":true},{"name":"scaleBps","type":"uint16","indexed":false}],"anonymous":false},
  {"type":"event","name":"Published","inputs":[{"name":"desk","type":"address","indexed":true},{"name":"name","type":"string","indexed":false}],"anonymous":false},
  {"type":"event","name":"Unfollowed","inputs":[{"name":"leader","type":"address","indexed":true},{"name":"follower","type":"address","indexed":true}],"anonymous":false},
  {"type":"event","name":"Unpublished","inputs":[{"name":"desk","type":"address","indexed":true}],"anonymous":false},
  {"type":"error","name":"DeskExists","inputs":[{"name":"desk","type":"address"}]},
  {"type":"error","name":"FailedDeployment","inputs":[]},
  {"type":"error","name":"FollowerLimit","inputs":[]},
  {"type":"error","name":"InsufficientBalance","inputs":[{"name":"balance","type":"uint256"},{"name":"needed","type":"uint256"}]},
  {"type":"error","name":"InvalidScale","inputs":[{"name":"scaleBps","type":"uint16"}]},
  {"type":"error","name":"NoDesk","inputs":[]},
  {"type":"error","name":"NotFollowing","inputs":[{"name":"leader","type":"address"}]},
  {"type":"error","name":"NotPublished","inputs":[{"name":"desk","type":"address"}]},
  {"type":"error","name":"SelfFollow","inputs":[]},
  {"type":"error","name":"ZeroAddress","inputs":[]},
] as const

export const brainAbi = [
  {"type":"constructor","inputs":[{"name":"owner_","type":"address"},{"name":"platform_","type":"address"}],"stateMutability":"nonpayable"},
  {"type":"receive","stateMutability":"payable"},
  {"type":"function","name":"AGENT_ID","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"DEFAULT_FEED_AGENT_ID","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"DEFAULT_MAX_FEED_AGE_MILLIS","inputs":[],"outputs":[{"name":"","type":"uint64"}],"stateMutability":"view"},
  {"type":"function","name":"DEFAULT_MIN_SOURCES","inputs":[],"outputs":[{"name":"","type":"uint8"}],"stateMutability":"view"},
  {"type":"function","name":"DEFAULT_ORACLE_AGENT_ID","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"MAX_SLACK","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"MIN_SLACK","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"PLATFORM","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"committeeSize","inputs":[],"outputs":[{"name":"","type":"uint8"}],"stateMutability":"view"},
  {"type":"function","name":"committeeThreshold","inputs":[],"outputs":[{"name":"","type":"uint8"}],"stateMutability":"view"},
  {"type":"function","name":"decodeOracleReading","inputs":[{"name":"result","type":"bytes"}],"outputs":[{"name":"price","type":"uint256"},{"name":"numSources","type":"uint8"},{"name":"lastUpdated","type":"uint64"}],"stateMutability":"pure"},
  {"type":"function","name":"feedAgentId","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"feedCommitteeSize","inputs":[],"outputs":[{"name":"","type":"uint8"}],"stateMutability":"view"},
  {"type":"function","name":"feedLatencyEma","inputs":[],"outputs":[{"name":"","type":"uint64"}],"stateMutability":"view"},
  {"type":"function","name":"feedObserved","inputs":[],"outputs":[{"name":"","type":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"feedOf","inputs":[{"name":"assetKey","type":"bytes32"}],"outputs":[{"name":"","type":"tuple","components":[{"name":"kind","type":"uint8"},{"name":"symbol","type":"string"},{"name":"url","type":"string"},{"name":"selector","type":"string"},{"name":"decimals","type":"uint8"}]}],"stateMutability":"view"},
  {"type":"function","name":"feedThreshold","inputs":[],"outputs":[{"name":"","type":"uint8"}],"stateMutability":"view"},
  {"type":"function","name":"handlePrice","inputs":[{"name":"requestId","type":"uint256"},{"name":"responses","type":"tuple[]","components":[{"name":"validator","type":"address"},{"name":"result","type":"bytes"},{"name":"status","type":"uint8"},{"name":"receipt","type":"uint256"},{"name":"timestamp","type":"uint256"},{"name":"executionCost","type":"uint256"}]},{"name":"status","type":"uint8"},{"name":"","type":"tuple","components":[{"name":"id","type":"uint256"},{"name":"requester","type":"address"},{"name":"callbackAddress","type":"address"},{"name":"callbackSelector","type":"bytes4"},{"name":"subcommittee","type":"address[]"},{"name":"responses","type":"tuple[]","components":[{"name":"validator","type":"address"},{"name":"result","type":"bytes"},{"name":"status","type":"uint8"},{"name":"receipt","type":"uint256"},{"name":"timestamp","type":"uint256"},{"name":"executionCost","type":"uint256"}]},{"name":"responseCount","type":"uint256"},{"name":"failureCount","type":"uint256"},{"name":"threshold","type":"uint256"},{"name":"createdAt","type":"uint256"},{"name":"deadline","type":"uint256"},{"name":"status","type":"uint8"},{"name":"consensusType","type":"uint8"},{"name":"remainingBudget","type":"uint256"},{"name":"perAgentBudget","type":"uint256"}]}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"handleResponse","inputs":[{"name":"requestId","type":"uint256"},{"name":"responses","type":"tuple[]","components":[{"name":"validator","type":"address"},{"name":"result","type":"bytes"},{"name":"status","type":"uint8"},{"name":"receipt","type":"uint256"},{"name":"timestamp","type":"uint256"},{"name":"executionCost","type":"uint256"}]},{"name":"status","type":"uint8"},{"name":"","type":"tuple","components":[{"name":"id","type":"uint256"},{"name":"requester","type":"address"},{"name":"callbackAddress","type":"address"},{"name":"callbackSelector","type":"bytes4"},{"name":"subcommittee","type":"address[]"},{"name":"responses","type":"tuple[]","components":[{"name":"validator","type":"address"},{"name":"result","type":"bytes"},{"name":"status","type":"uint8"},{"name":"receipt","type":"uint256"},{"name":"timestamp","type":"uint256"},{"name":"executionCost","type":"uint256"}]},{"name":"responseCount","type":"uint256"},{"name":"failureCount","type":"uint256"},{"name":"threshold","type":"uint256"},{"name":"createdAt","type":"uint256"},{"name":"deadline","type":"uint256"},{"name":"status","type":"uint8"},{"name":"consensusType","type":"uint8"},{"name":"remainingBudget","type":"uint256"},{"name":"perAgentBudget","type":"uint256"}]}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"marketOfPriceRequest","inputs":[{"name":"requestId","type":"uint256"}],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"marketOfRequest","inputs":[{"name":"requestId","type":"uint256"}],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"maxFeedAgeMillis","inputs":[],"outputs":[{"name":"","type":"uint64"}],"stateMutability":"view"},
  {"type":"function","name":"minSources","inputs":[],"outputs":[{"name":"","type":"uint8"}],"stateMutability":"view"},
  {"type":"function","name":"oracleAgentId","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"owner","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"quote","inputs":[],"outputs":[{"name":"weiNeeded","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"quoteStage1","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"quoteStage2","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"renounceOwnership","inputs":[],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"requestVerdict","inputs":[{"name":"marketId","type":"bytes32"},{"name":"m","type":"tuple","components":[{"name":"marketId","type":"bytes32"},{"name":"market","type":"address"},{"name":"pool","type":"address"},{"name":"operatorId","type":"uint32"},{"name":"venueId","type":"bytes32"},{"name":"yesId","type":"uint256"},{"name":"noId","type":"uint256"},{"name":"tradingStart","type":"uint64"},{"name":"expiry","type":"uint64"},{"name":"nonce","type":"uint64"},{"name":"strike","type":"uint256"},{"name":"assetKey","type":"bytes32"},{"name":"intervalSec","type":"uint32"}]},{"name":"pBookBps","type":"uint256"},{"name":"recentOutcomes","type":"uint16[]"}],"outputs":[{"name":"requestId","type":"uint256"}],"stateMutability":"payable"},
  {"type":"function","name":"requiredSlack","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"router","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"setCommittee","inputs":[{"name":"size","type":"uint8"},{"name":"threshold","type":"uint8"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setFeed","inputs":[{"name":"assetKey","type":"bytes32"},{"name":"kind","type":"uint8"},{"name":"symbol","type":"string"},{"name":"url","type":"string"},{"name":"selector","type":"string"},{"name":"decimals","type":"uint8"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setFeedAgent","inputs":[{"name":"agentId","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setFeedCommittee","inputs":[{"name":"size","type":"uint8"},{"name":"threshold","type":"uint8"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setFeedGuards","inputs":[{"name":"maxAgeMillis","type":"uint64"},{"name":"minSources_","type":"uint8"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setOracleAgent","inputs":[{"name":"agentId","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setPrompt","inputs":[{"name":"system","type":"string"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setRouter","inputs":[{"name":"router_","type":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"sweep","inputs":[{"name":"to","type":"address"},{"name":"amount","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"systemPrompt","inputs":[],"outputs":[{"name":"","type":"string"}],"stateMutability":"view"},
  {"type":"function","name":"transferOwnership","inputs":[{"name":"newOwner","type":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"verdictLatencyEma","inputs":[],"outputs":[{"name":"","type":"uint64"}],"stateMutability":"view"},
  {"type":"function","name":"verdictObserved","inputs":[],"outputs":[{"name":"","type":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"verdictOf","inputs":[{"name":"marketId","type":"bytes32"}],"outputs":[{"name":"","type":"tuple","components":[{"name":"probUpBps","type":"uint16"},{"name":"responded","type":"uint8"},{"name":"agreed","type":"uint8"},{"name":"ok","type":"bool"},{"name":"requestId","type":"uint256"}]}],"stateMutability":"view"},
  {"type":"event","name":"CommitteeUpdated","inputs":[{"name":"size","type":"uint8","indexed":false},{"name":"threshold","type":"uint8","indexed":false}],"anonymous":false},
  {"type":"event","name":"FeedAgentUpdated","inputs":[{"name":"agentId","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"FeedCommitteeUpdated","inputs":[{"name":"size","type":"uint8","indexed":false},{"name":"threshold","type":"uint8","indexed":false}],"anonymous":false},
  {"type":"event","name":"FeedGuardsUpdated","inputs":[{"name":"maxFeedAgeMillis","type":"uint64","indexed":false},{"name":"minSources","type":"uint8","indexed":false}],"anonymous":false},
  {"type":"event","name":"FeedUpdated","inputs":[{"name":"assetKey","type":"bytes32","indexed":true},{"name":"kind","type":"uint8","indexed":false},{"name":"symbol","type":"string","indexed":false},{"name":"url","type":"string","indexed":false},{"name":"selector","type":"string","indexed":false},{"name":"decimals","type":"uint8","indexed":false}],"anonymous":false},
  {"type":"event","name":"LateAbort","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"secondsLeft","type":"uint256","indexed":false},{"name":"needed","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"LatencyObserved","inputs":[{"name":"stage","type":"uint8","indexed":true},{"name":"observed","type":"uint256","indexed":false},{"name":"ema","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"NoFeed","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"assetKey","type":"bytes32","indexed":true}],"anonymous":false},
  {"type":"event","name":"OracleAgentUpdated","inputs":[{"name":"agentId","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"OwnershipTransferred","inputs":[{"name":"previousOwner","type":"address","indexed":true},{"name":"newOwner","type":"address","indexed":true}],"anonymous":false},
  {"type":"event","name":"PriceGuardRejected","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"requestId","type":"uint256","indexed":true},{"name":"stale","type":"uint8","indexed":false},{"name":"thin","type":"uint8","indexed":false}],"anonymous":false},
  {"type":"event","name":"PriceReceived","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"requestId","type":"uint256","indexed":true},{"name":"spot","type":"uint256","indexed":false},{"name":"used","type":"uint8","indexed":false},{"name":"prices","type":"uint256[]","indexed":false}],"anonymous":false},
  {"type":"event","name":"PriceRequested","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"requestId","type":"uint256","indexed":true},{"name":"assetKey","type":"bytes32","indexed":true},{"name":"deposit","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"PriceUnusable","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"requestId","type":"uint256","indexed":true}],"anonymous":false},
  {"type":"event","name":"PromptUpdated","inputs":[{"name":"system","type":"string","indexed":false}],"anonymous":false},
  {"type":"event","name":"RouterCallFailed","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"requestId","type":"uint256","indexed":true}],"anonymous":false},
  {"type":"event","name":"RouterUpdated","inputs":[{"name":"router","type":"address","indexed":false}],"anonymous":false},
  {"type":"event","name":"StageTwoUnfunded","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"needed","type":"uint256","indexed":false},{"name":"available","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"Swept","inputs":[{"name":"to","type":"address","indexed":true},{"name":"amount","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"VerdictReceived","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"requestId","type":"uint256","indexed":true},{"name":"probUpBps","type":"uint16","indexed":false},{"name":"responded","type":"uint8","indexed":false},{"name":"agreed","type":"uint8","indexed":false},{"name":"ok","type":"bool","indexed":false},{"name":"scores","type":"int256[]","indexed":false}],"anonymous":false},
  {"type":"event","name":"VerdictRequested","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"requestId","type":"uint256","indexed":true},{"name":"size","type":"uint8","indexed":false},{"name":"threshold","type":"uint8","indexed":false},{"name":"deposit","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"VerdictTooLate","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"expiry","type":"uint256","indexed":false},{"name":"arrivedAt","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"WindowTooTight","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"secondsLeft","type":"uint256","indexed":false},{"name":"requiredSlack","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"error","name":"BadCommittee","inputs":[{"name":"size","type":"uint8"},{"name":"threshold","type":"uint8"}]},
  {"type":"error","name":"BadFeed","inputs":[]},
  {"type":"error","name":"BadFeedGuard","inputs":[{"name":"maxAgeMillis","type":"uint64"},{"name":"minSources","type":"uint8"}]},
  {"type":"error","name":"NotAuthorized","inputs":[]},
  {"type":"error","name":"NotPlatform","inputs":[]},
  {"type":"error","name":"OwnableInvalidOwner","inputs":[{"name":"owner","type":"address"}]},
  {"type":"error","name":"OwnableUnauthorizedAccount","inputs":[{"name":"account","type":"address"}]},
  {"type":"error","name":"SweepFailed","inputs":[]},
  {"type":"error","name":"Underfunded","inputs":[{"name":"needed","type":"uint256"},{"name":"available","type":"uint256"}]},
  {"type":"error","name":"UnknownRequest","inputs":[{"name":"requestId","type":"uint256"}]},
  {"type":"error","name":"ZeroAddress","inputs":[]},
  {"type":"error","name":"ZeroPlatform","inputs":[]},
] as const

export const keeperAbi = [
  {"type":"constructor","inputs":[{"name":"owner_","type":"address"},{"name":"router_","type":"address"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"READ_GAS","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"UPKEEP_GAS","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"WHAT_FINALIZE","inputs":[],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"WHAT_MODULE","inputs":[],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"WHAT_POKE","inputs":[],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"WHAT_RELEASE","inputs":[],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"WHAT_SYNC","inputs":[],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"WHAT_VOID","inputs":[],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"counts","inputs":[],"outputs":[{"name":"finalized","type":"uint64"},{"name":"released","type":"uint64"},{"name":"synced","type":"uint64"},{"name":"poked","type":"uint64"},{"name":"voided","type":"uint64"},{"name":"failures","type":"uint64"}],"stateMutability":"view"},
  {"type":"function","name":"keep","inputs":[{"name":"m","type":"tuple","components":[{"name":"marketId","type":"bytes32"},{"name":"market","type":"address"},{"name":"pool","type":"address"},{"name":"operatorId","type":"uint32"},{"name":"venueId","type":"bytes32"},{"name":"yesId","type":"uint256"},{"name":"noId","type":"uint256"},{"name":"tradingStart","type":"uint64"},{"name":"expiry","type":"uint64"},{"name":"nonce","type":"uint64"},{"name":"strike","type":"uint256"},{"name":"assetKey","type":"bytes32"},{"name":"intervalSec","type":"uint32"}]}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"owner","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"renounceOwnership","inputs":[],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"router","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"setRouter","inputs":[{"name":"router_","type":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"transferOwnership","inputs":[{"name":"newOwner","type":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"event","name":"KeepFailed","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"what","type":"bytes32","indexed":false},{"name":"reason","type":"bytes","indexed":false}],"anonymous":false},
  {"type":"event","name":"Kept","inputs":[{"name":"marketId","type":"bytes32","indexed":true},{"name":"what","type":"bytes32","indexed":false}],"anonymous":false},
  {"type":"event","name":"OwnershipTransferred","inputs":[{"name":"previousOwner","type":"address","indexed":true},{"name":"newOwner","type":"address","indexed":true}],"anonymous":false},
  {"type":"event","name":"RouterSet","inputs":[{"name":"router","type":"address","indexed":false}],"anonymous":false},
  {"type":"error","name":"NotRouter","inputs":[]},
  {"type":"error","name":"OwnableInvalidOwner","inputs":[{"name":"owner","type":"address"}]},
  {"type":"error","name":"OwnableUnauthorizedAccount","inputs":[{"name":"account","type":"address"}]},
] as const

export const relayAbi = [
  {"type":"constructor","inputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"DOMAIN_SEPARATOR","inputs":[],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"MAX_PENDING","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"MODULE","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"REDEEM_AUTHORIZATION_TYPE","inputs":[],"outputs":[{"name":"","type":"string"}],"stateMutability":"view"},
  {"type":"function","name":"REDEEM_AUTHORIZATION_TYPEHASH","inputs":[],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"cancel","inputs":[{"name":"marketId","type":"bytes32"},{"name":"index","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"digestOf","inputs":[{"name":"a","type":"tuple","components":[{"name":"owner","type":"address"},{"name":"operatorId","type":"uint32"},{"name":"venueId","type":"bytes32"},{"name":"marketId","type":"bytes32"},{"name":"outcomeIdx","type":"uint8"},{"name":"amount","type":"uint256"},{"name":"nonce","type":"uint256"},{"name":"deadline","type":"uint256"}]}],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"failedCount","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"pendingCount","inputs":[{"name":"marketId","type":"bytes32"}],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"pendingFor","inputs":[{"name":"marketId","type":"bytes32"}],"outputs":[{"name":"","type":"tuple[]","components":[{"name":"owner","type":"address"},{"name":"operatorId","type":"uint32"},{"name":"venueId","type":"bytes32"},{"name":"marketId","type":"bytes32"},{"name":"outcomeIdx","type":"uint8"},{"name":"amount","type":"uint256"},{"name":"nonce","type":"uint256"},{"name":"deadline","type":"uint256"}]}],"stateMutability":"view"},
  {"type":"function","name":"pendingSignatureFor","inputs":[{"name":"marketId","type":"bytes32"},{"name":"index","type":"uint256"}],"outputs":[{"name":"","type":"bytes"}],"stateMutability":"view"},
  {"type":"function","name":"relay","inputs":[{"name":"marketId","type":"bytes32"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"relayUpTo","inputs":[{"name":"marketId","type":"bytes32"},{"name":"max","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"relayedCount","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"submit","inputs":[{"name":"a","type":"tuple","components":[{"name":"owner","type":"address"},{"name":"operatorId","type":"uint32"},{"name":"venueId","type":"bytes32"},{"name":"marketId","type":"bytes32"},{"name":"outcomeIdx","type":"uint8"},{"name":"amount","type":"uint256"},{"name":"nonce","type":"uint256"},{"name":"deadline","type":"uint256"}]},{"name":"sig","type":"bytes"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"usedNonce","inputs":[{"name":"","type":"address"},{"name":"","type":"uint256"}],"outputs":[{"name":"","type":"bool"}],"stateMutability":"view"},
  {"type":"event","name":"Cancelled","inputs":[{"name":"owner","type":"address","indexed":true},{"name":"marketId","type":"bytes32","indexed":true}],"anonymous":false},
  {"type":"event","name":"RelayFailed","inputs":[{"name":"owner","type":"address","indexed":true},{"name":"marketId","type":"bytes32","indexed":true},{"name":"reason","type":"bytes","indexed":false}],"anonymous":false},
  {"type":"event","name":"Relayed","inputs":[{"name":"owner","type":"address","indexed":true},{"name":"marketId","type":"bytes32","indexed":true},{"name":"outcomeIdx","type":"uint8","indexed":false},{"name":"amount","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"Submitted","inputs":[{"name":"owner","type":"address","indexed":true},{"name":"marketId","type":"bytes32","indexed":true},{"name":"outcomeIdx","type":"uint8","indexed":false},{"name":"amount","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"error","name":"BadSignature","inputs":[]},
  {"type":"error","name":"Expired","inputs":[]},
  {"type":"error","name":"IndexOutOfRange","inputs":[]},
  {"type":"error","name":"NonceUsed","inputs":[]},
  {"type":"error","name":"NotAuthorizationOwner","inputs":[]},
  {"type":"error","name":"QueueFull","inputs":[]},
  {"type":"error","name":"Reentrant","inputs":[]},
] as const

export const seriesAbi = [
  {"type":"constructor","inputs":[{"name":"owner_","type":"address"},{"name":"router_","type":"address"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"DEFAULT_MAX_ROLLS_PER_DAY","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"DEFAULT_MIN_CREATOR_FLOAT","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"GAS_RESERVE","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"MIN_ROLL_GAS","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"MIN_STALENESS","inputs":[],"outputs":[{"name":"","type":"uint32"}],"stateMutability":"view"},
  {"type":"function","name":"REASON_DAILY_CAP","inputs":[],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"REASON_LOW_FLOAT","inputs":[],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"REASON_NO_GAS","inputs":[],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"REASON_NO_SERIES","inputs":[],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"REASON_OFF","inputs":[],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"REASON_TOO_SOON","inputs":[],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"REASON_VENUE_HEALTHY","inputs":[],"outputs":[{"name":"","type":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"ROLL_GAS","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"STALENESS_MULTIPLE","inputs":[],"outputs":[{"name":"","type":"uint32"}],"stateMutability":"view"},
  {"type":"function","name":"creator","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"dayKey","inputs":[],"outputs":[{"name":"","type":"uint64"}],"stateMutability":"view"},
  {"type":"function","name":"fund","inputs":[],"outputs":[],"stateMutability":"payable"},
  {"type":"function","name":"intervalSec","inputs":[],"outputs":[{"name":"","type":"uint32"}],"stateMutability":"view"},
  {"type":"function","name":"lastRollAt","inputs":[],"outputs":[{"name":"","type":"uint64"}],"stateMutability":"view"},
  {"type":"function","name":"lastVenueMarketAt","inputs":[],"outputs":[{"name":"","type":"uint64"}],"stateMutability":"view"},
  {"type":"function","name":"maxRollsPerDay","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"minCreatorFloat","inputs":[],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"mode","inputs":[],"outputs":[{"name":"","type":"uint8"}],"stateMutability":"view"},
  {"type":"function","name":"onTick","inputs":[{"name":"","type":"tuple","components":[{"name":"marketId","type":"bytes32"},{"name":"market","type":"address"},{"name":"pool","type":"address"},{"name":"operatorId","type":"uint32"},{"name":"venueId","type":"bytes32"},{"name":"yesId","type":"uint256"},{"name":"noId","type":"uint256"},{"name":"tradingStart","type":"uint64"},{"name":"expiry","type":"uint64"},{"name":"nonce","type":"uint64"},{"name":"strike","type":"uint256"},{"name":"assetKey","type":"bytes32"},{"name":"intervalSec","type":"uint32"}]}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"onVenueMarket","inputs":[{"name":"m","type":"tuple","components":[{"name":"marketId","type":"bytes32"},{"name":"market","type":"address"},{"name":"pool","type":"address"},{"name":"operatorId","type":"uint32"},{"name":"venueId","type":"bytes32"},{"name":"yesId","type":"uint256"},{"name":"noId","type":"uint256"},{"name":"tradingStart","type":"uint64"},{"name":"expiry","type":"uint64"},{"name":"nonce","type":"uint64"},{"name":"strike","type":"uint256"},{"name":"assetKey","type":"bytes32"},{"name":"intervalSec","type":"uint32"}]}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"owner","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"renounceOwnership","inputs":[],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"rollNow","inputs":[],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"rollsToday","inputs":[],"outputs":[{"name":"","type":"uint32"}],"stateMutability":"view"},
  {"type":"function","name":"router","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
  {"type":"function","name":"seriesId","inputs":[],"outputs":[{"name":"","type":"uint32"}],"stateMutability":"view"},
  {"type":"function","name":"setBudget","inputs":[{"name":"maxRollsPerDay_","type":"uint256"},{"name":"minCreatorFloat_","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setMode","inputs":[{"name":"m","type":"uint8"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setRouter","inputs":[{"name":"router_","type":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setSeries","inputs":[{"name":"creator_","type":"address"},{"name":"seriesId_","type":"uint32"},{"name":"intervalSec_","type":"uint32"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setStaleness","inputs":[{"name":"seconds_","type":"uint32"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"stalenessOverride","inputs":[],"outputs":[{"name":"","type":"uint32"}],"stateMutability":"view"},
  {"type":"function","name":"stalenessSeconds","inputs":[],"outputs":[{"name":"","type":"uint32"}],"stateMutability":"view"},
  {"type":"function","name":"status","inputs":[],"outputs":[{"name":"","type":"uint8"},{"name":"","type":"bool"},{"name":"","type":"uint64"},{"name":"","type":"uint64"},{"name":"","type":"uint32"},{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"transferOwnership","inputs":[{"name":"newOwner","type":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"withdrawNative","inputs":[{"name":"to","type":"address"},{"name":"amount","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"event","name":"BudgetSet","inputs":[{"name":"maxRollsPerDay","type":"uint256","indexed":false},{"name":"minCreatorFloat","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"Funded","inputs":[{"name":"from","type":"address","indexed":true},{"name":"amount","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"ModeSet","inputs":[{"name":"mode","type":"uint8","indexed":false}],"anonymous":false},
  {"type":"event","name":"OwnershipTransferred","inputs":[{"name":"previousOwner","type":"address","indexed":true},{"name":"newOwner","type":"address","indexed":true}],"anonymous":false},
  {"type":"event","name":"RollFailed","inputs":[{"name":"seriesId","type":"uint32","indexed":true},{"name":"reason","type":"bytes","indexed":false}],"anonymous":false},
  {"type":"event","name":"RollSkipped","inputs":[{"name":"reason","type":"bytes32","indexed":true}],"anonymous":false},
  {"type":"event","name":"Rolled","inputs":[{"name":"seriesId","type":"uint32","indexed":true},{"name":"gasUsed","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"event","name":"RouterSet","inputs":[{"name":"router","type":"address","indexed":false}],"anonymous":false},
  {"type":"event","name":"SeriesSet","inputs":[{"name":"creator","type":"address","indexed":false},{"name":"seriesId","type":"uint32","indexed":false},{"name":"intervalSec","type":"uint32","indexed":false}],"anonymous":false},
  {"type":"event","name":"StalenessSet","inputs":[{"name":"stalenessSeconds","type":"uint32","indexed":false}],"anonymous":false},
  {"type":"event","name":"Withdrawn","inputs":[{"name":"to","type":"address","indexed":true},{"name":"amount","type":"uint256","indexed":false}],"anonymous":false},
  {"type":"error","name":"BadInterval","inputs":[]},
  {"type":"error","name":"NotRouter","inputs":[]},
  {"type":"error","name":"OwnableInvalidOwner","inputs":[{"name":"owner","type":"address"}]},
  {"type":"error","name":"OwnableUnauthorizedAccount","inputs":[{"name":"account","type":"address"}]},
  {"type":"error","name":"WithdrawFailed","inputs":[]},
  {"type":"error","name":"ZeroAddress","inputs":[]},
] as const

export const collateralAbi = [
  {"type":"function","name":"approve","inputs":[{"name":"spender","type":"address"},{"name":"amount","type":"uint256"}],"outputs":[{"name":"","type":"bool"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"balanceOf","inputs":[{"name":"account","type":"address"}],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"decimals","inputs":[],"outputs":[{"name":"","type":"uint8"}],"stateMutability":"view"},
  {"type":"function","name":"faucet","inputs":[{"name":"amount","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"transfer","inputs":[{"name":"to","type":"address"},{"name":"amount","type":"uint256"}],"outputs":[{"name":"","type":"bool"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"transferFrom","inputs":[{"name":"from","type":"address"},{"name":"to","type":"address"},{"name":"amount","type":"uint256"}],"outputs":[{"name":"","type":"bool"}],"stateMutability":"nonpayable"},
] as const
